### ISSUE TITLE
Problema para rodar o projeto

### ISSUE THREAD

**Issue by sotnaspina** [odranoelBR/vue-quasar-admin-example#24]
Instalei tudo, mas quando tento rodar o projeto dá o erro abaixo, tem mais alguma configuração pra fazer?

Grato.

$ npm run dev

> quasar-app@0.0.1 dev E:\desenvolvimento\web\project-admin
> node build/script.dev.js

 Starting dev server with "mat" theme...
 Will listen at http://localhost:8080
 Browser will open when build is ready.

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.listen (E:\desenvolvimento\web\project-admin\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (E:\desenvolvimento\web\project-admin\build\script.dev.js:74:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quasar-app@0.0.1 dev: `node build/script.dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quasar-app@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by sotnaspina** [comment]
Como que eu passo uma porta diferente como parâmetro? tentei npm run dev -p 8888, mas nd
